name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

change-template: "* $TITLE"
change-title-escapes: '\<*_&' # to avoid formatting issues

version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch"]
  default: patch

template: |
  $CHANGES
