name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: "🚀 Added"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixed"
    labels: ["fix", "bug"]
  - title: "🔄 Updated"
    labels: ["chore", "refactor"]
  - title: "🗑️ Removed"
    labels: ["removed"]

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # to avoid formatting issues

version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch"]
  default: patch

template: |
  ## Changes

  $CHANGES
